### ISSUE TITLE
Move ThreeDEntities from examples_common.nim into entities.nim

### ISSUE THREAD

**Issue by EriKWDev** [paranim/paranim#1]
I don't understand the reasoning behind putting primitives that are 3D inside `primitives.nim` without providing a basic ThreeDEntity out of the box. Couldn't all work that's been put into the `examples_common.nim` just be moved into `entities.nim`? :)

It seems like an awful lot of boilerplate that is very same-y to 2D (rotation, translation, scaling... ) in order to create 3D entities when the ones from the examples could just as well be part of the package. Is there any reason that they are not? And if the argument is that we should write our own entities, why are TwoDEntity and ImageEntity included?

**Comment by oakes** [comment]
My reasoning was that it is very likely you'll need to make a custom entity anyway if you're doing 3D stuff. It's not likely that the ThreeDEntity will be useful to you for long unless you are just trying to draw a single 3D shape with really basic coloring and no lighting. So it would probably be better to just copy that stuff into your project so you can immediately start to customize the shaders and whatnot. With the 2D entities you can go for a long time using the built-in entities because it's common to need to render an image or simple shape.

**Comment by EriKWDev** [comment]
That is a fair point. There would be little use for 3D without being able to control parameters and the shader, which would involve creating your own entity...

There might be a compromise here that I'm not seeing at the moment.. It would be nice for translations, rotations, projections, scaling etc, to have the 3D versions built-in given that any entity, 2d or 3d, will have coordinates... and those procs in example_common seemed to just be overloadings of the ones already present with an extra added z-coordinate? (As well as rotation along axes...)

**Comment by oakes** [comment]
Yeah i think those functions will need to be implemented for each custom entity. There isn't really a way to make functions like `translate` that work for all 3D entities because they could change depending on how the shader is written. For example:

```nim
proc translate*[UniT, AttrT](entity: var Entity[UniT, AttrT], x: GLfloat, y: GLfloat, z: GLfloat) =
  entity.uniforms.u_matrix.translate(x, y, z)
```

This function assumes that the shader has a uniform called `u_matrix`, so it won't work if you rename it to something else. TwoDEntity and ImageEntity can share these functions because they both happen to have the same uniform in their shaders, but I can't assume that about custom entities that people create.

**Comment by EriKWDev** [comment]
While I personally wouldn't mind having a name restriction on the coordinate matrix in the shader as a cost to being able to use the procs directly from the library, I can see why such a solution might not fit the goal of this package.

Thank you for quick input, and for a very nifty package nevertheless :)
